import { test, expect } from 'vitest'

import * as G from '../../src/exports/Exports.js'
import * as R from 'regexp-composer'
import { writeScratchpadOutputToDisk } from '../utilities/Utilities.js'

////////////////////////////////////////////////////////////////////////////
// Agents:
//
// You can use this directory to write temporary tests,
// build grammars and observe the resulting parse trees.
// `writeScratchpadOutputToDisk` will write them in the `./out` local directory.
// It writes both a `.json` file for the full object and a `.parsetree` plaintext file
// with only the minimal structure of the tree.
//
// **Please do not edit this file. It is meant for illustration only.**
////////////////////////////////////////////////////////////////////////////

test('Scratchpad test', () => {
	class TestGrammar {
		root = () => ['a', 'b', 'c', G.anyOf('d', 'e')]
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	const parseTree = grammar.parse('abce')

	writeScratchpadOutputToDisk(parseTree, 'test')
})

test('Probe: bestOf longest match', () => {
	class TestGrammar {
		root = () => [G.bestOf('abc', 'abcdefg')]
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	expect(grammar.parse('abcdefg')).toMatchObject([{ name: 'root', sourceText: 'abcdefg' }])
	// PEG-ish 'anyOf' would match 'abc' only:
	const grammar2 = G.buildGrammar(class {
		root = () => [G.anyOf('abc', 'abcdefg')]
	}, 'root')

	expect(grammar2.parse('abcdefg')).toMatchObject([{ name: 'root', sourceText: 'abc' }])
})

test('Probe: zeroOrMore of productions', () => {
	class TestGrammar {
		root = () => [G.zeroOrMore(this.item)]

		item = () => ['a', G.possibly('b')]
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	const result = grammar.parse('ababab')
	console.log('zeroOrMore result:', JSON.stringify(result, undefined, 2))

	expect(result).toMatchObject([{ name: 'root', sourceText: 'ababab' }])
})

test('Probe: pattern with named captures', () => {
	class TestGrammar {
		root = () => G.pattern([
			R.captureAs('first', R.oneOrMore(R.charRange('a', 'z'))),
			'-',
			R.captureAs('second', R.oneOrMore(R.charRange('0', '9'))),
		])
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	const result = grammar.parse('abc-123')
	console.log('pattern result:', JSON.stringify(result, undefined, 2))
})

test('Probe: parse error reporting', () => {
	class TestGrammar {
		root = () => ['a', G.anyOf('b', 'c'), 'd']
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	try {
		grammar.parse('abx')
	}
	catch (error: any) {
		console.log('ParseError message:', error.message)
	}
})

test('Probe: incomplete parse error', () => {
	class TestGrammar {
		root = () => ['a', 'b', 'c', 'd']
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	try {
		grammar.parse('abc')
	}
	catch (error: any) {
		console.log('Incomplete error message:', error.message)
	}
})

test('Probe: cached elements', () => {
	class TestGrammar {
		root = () => [G.zeroOrMore(this.item)]

		item = () => G.cached(G.anyOf('ab', 'a', 'abc'))
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	const result = grammar.parse('ababcab')
	console.log('cached result:', JSON.stringify(result, undefined, 2))
})

test('Probe: nested optional + repetition', () => {
	class TestGrammar {
		root = () => [G.possibly(this.list), 'z']

		list = () => [G.zeroOrMore(this.item)]

		item = () => ['a']
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	const result = grammar.parse('aaaaz')
	console.log('nested optional result:', JSON.stringify(result, undefined, 2))
})
