import { test, expect } from 'vitest'

import * as G from '../../src/exports/Exports.js'
import { writeScratchpadOutputToDisk } from '../utilities/Utilities.js'

////////////////////////////////////////////////////////////////////////////
// Agents:
//
// You can use this directory to write temporary tests,
// build grammars and observe the resulting parse trees.
// `writeScratchpadOutputToDisk` will write them in the `./out` local directory.
// It writes both a `.json` file for the full object and a `.parsetree` plaintext file
// with only the minimal structure of the tree.
//
// **Please do not edit this file. It is meant for illustration only.**
////////////////////////////////////////////////////////////////////////////

test('Scratchpad test', () => {
	class TestGrammar {
		root = () => ['a', 'b', 'c', G.anyOf('d', 'e')]
	}

	const grammar = G.buildGrammar(TestGrammar, 'root')

	const parseTree = grammar.parse('abce')

	writeScratchpadOutputToDisk(parseTree, 'test')
})
